"""add phone number to users table

Revision ID: 23f14cd5c695
Revises: c96d94c42900
Create Date: 2024-01-29 15:55:49.302017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23f14cd5c695'
down_revision: Union[str, None] = 'c96d94c42900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users',sa.Column('phone_number',sa.String(),nullable = True))
   
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users','phone_number')
    # ### end Alembic commands ###
